version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Australia/Sydney
    open-pull-requests-limit: 5
    groups:
      react-runtime:
        patterns:
          - react
          - react-dom
        update-types:
          - major
          - minor
          - patch
      production-minor-patches:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-minor-patches:
        dependency-type: development
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
